networks:
  penpot:
    external: true
    name: localdev

services:
  frontend:
    image: "penpotapp/frontend:latest"
    container_name: penpot-frontend
    networks:
      - penpot
    restart: always
    env_file:
      - ./docker/.env
    environment:
      VIRTUAL_HOST: penpot.docker
      NODE_ENV: dev
      PENPOT_FLAGS: disable-secure-session-cookies enable-demo-users enable-registration enable-login-with-password
    ports:
      - "9001:80"
    depends_on:
      - backend
      - exporter
    volumes:
      - penpot_assets:/opt/data/assets

  backend:
    image: "penpotapp/backend:latest"
    container_name: penpot-backend
    restart: always
    networks:
      - penpot
    depends_on:
      - postgres
      - redis
    volumes:
      - penpot_assets:/opt/data/assets
    env_file:
      - ./docker/.env
    environment:
      PENPOT_FLAGS: disable-secure-session-cookies enable-registration enable-demo-users enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      PENPOT_PREPL_HOST: 0.0.0.0
      # this was previously http://localhost:9001
      PENPOT_PUBLIC_URI: http://penpot.docker:9001
      PENPOT_REDIS_URI: redis://penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: false

  exporter:
    image: "penpotapp/exporter:latest"
    container_name: penpot-exporter
    networks:
      - penpot
    restart: always
    env_file:
      - ./docker/.env

  postgres:
    image: "postgres:15"
    container_name: penpot-postgres
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - penpot
    restart: always
    stop_signal: SIGINT
    env_file:
      - ./docker/.env

  redis:
    image: redis:7
    container_name: penpot-redis
    networks:
      - penpot
    restart: always
    env_file:
      - ./docker/.env

  # used as temporary SMTP server.
  mailcatch:
    image: sj26/mailcatcher:latest
    container_name: penpot-mailcatch
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot

volumes:
  penpot_postgres_v15:
  penpot_assets:
